additionalProperties:
  packageName: Supernova
  sourceFolder: .
  disallowAdditionalPropertiesIfNotPresent: false
  validatable: false
  
# languageSpecificPrimitive:
#   - Address
#   - AddressID
#   - AddressType
#   - AddrLine1
#   - AddrLine2
#   - AddrLine3
#   - AlternativeIdentifier
#   - Altitude
#   - AmountExtended
#   - Area
#   - Azimuth
#   - Calibration
#   - CalibrationDateLast
#   - CalibrationMeth
#   - CapacityDC
#   - CertificateValue
#   - CertificationAgency
#   - CertificationAgencyName
#   - CertificationDate
#   - CertificationExpirationDate
#   - CertificationName
#   - CertificationStandard
#   - Checksum
#   - ChecksumDetail
#   - ChecksumKey
#   - ChecksumType
#   - City
#   - Comment
#   - CommentDate
#   - CommentID
#   - CommentText
#   - Component
#   - ComponentName
#   - ComponentType
#   - ComponentUUID
#   - Connection
#   - ConnectionId
#   - ConnectionType
#   - Contact
#   - ContactID
#   - ContactTimezone
#   - ContactType
#   - Country
#   - County
#   - CreditRating
#   - CreditScore
#   - CreditScoreSource
#   - CryptographicKeyID
#   - Description
#   - Device1
#   - DeviceName
#   - DeviceType
#   - DeviceUUID
#   - Dimension
#   - Document
#   - DocumentDate
#   - DocumentId
#   - DocumentName
#   - DocumentType
#   - DocumentUrl
#   - Elevation
#   - Email
#   - Entity
#   - EntityRole
#   - FileFolderURL
#   - Firmware
#   - FirmwareVersion
#   - FirstName
#   - FromDeviceId
#   - GatewayHook
#   - GatewayHookExecution
#   - GatewayHookResult
#   - Height
#   - HomePhone
#   - HookStatus
#   - Identifier
#   - IdentifierType
#   - Info
#   - InServiceDate
#   - IsMaintainable
#   - LastName
#   - Latitude
#   - LegalEntityIdentifier
#   - Length
#   - Location
#   - LocationDeterminationMethod
#   - LocationID
#   - LocationType
#   - Longitude
#   - MaintDateLast
#   - ManufacturerUPC
#   - Mass
#   - MiddleName
#   - MobilePhone
#   - ModuleOrientation
#   - Node
#   - NodeUUID
#   - Orientation
#   - Package
#   - PaymentMethod
#   - PaymentMethodName
#   - PaymentToken
#   - PlatformIdentifier
#   - PreferredContactMethod
#   - ProdCertification
#   - ProdCode
#   - ProdDatasheet
#   - ProdID
#   - ProdInstruction
#   - ProdMfr
#   - ProdName
#   - ProdSpecification
#   - ProdType
#   - Product
#   - ProductLineItem
#   - PVArray1
#   - PVArrayID
#   - PVColladaFileID
#   - PVColladaID
#   - PVString1
#   - PVStringID
#   - PVSystem
#   - Quantity
#   - Roll
#   - RoofPlaneID
#   - Scope
#   - ScopeID
#   - ScopeType
#   - SerialNum
#   - SourceName
#   - SpecificationName
#   - SpecificationType
#   - SpecificationUnit
#   - SpecificationValue
#   - StateProvince
#   - SubstituteProduct
#   - SupportedDocument
#   - Tag
#   - TaxID
#   - TaxonomyElementBoolean
#   - TaxonomyElementInteger
#   - TaxonomyElementNumber
#   - TaxonomyElementString
#   - TestLab
#   - TestLabName
#   - Tilt
#   - Title
#   - ToDeviceId
#   - URL
#   - Warranty
#   - WarrantyDuration
#   - WarrantyEffectiveDate
#   - WarrantyExpirationDate
#   - WarrantyID
#   - WarrantyName
#   - WarrantyType
#   - Weight
#   - Width
#   - WorkPhone
#   - ZipPostalCode
# importMappings:
#   Address: OrangeButton.Models.Address
#   AddressID: OrangeButton.Models.AddressID
#   AddressType: OrangeButton.Models.AddressType
#   AddrLine1: OrangeButton.Models.AddrLine1
#   AddrLine2: OrangeButton.Models.AddrLine2
#   AddrLine3: OrangeButton.Models.AddrLine3
#   AlternativeIdentifier: OrangeButton.Models.AlternativeIdentifier
#   Altitude: OrangeButton.Models.Altitude
#   AmountExtended: OrangeButton.Models.AmountExtended
#   Area: OrangeButton.Models.Area
#   Azimuth: OrangeButton.Models.Azimuth
#   Calibration: OrangeButton.Models.Calibration
#   CalibrationDateLast: OrangeButton.Models.CalibrationDateLast
#   CalibrationMeth: OrangeButton.Models.CalibrationMeth
#   CapacityDC: OrangeButton.Models.CapacityDC
#   CertificateValue: OrangeButton.Models.CertificateValue
#   CertificationAgency: OrangeButton.Models.CertificationAgency
#   CertificationAgencyName: OrangeButton.Models.CertificationAgencyName
#   CertificationDate: OrangeButton.Models.CertificationDate
#   CertificationExpirationDate: OrangeButton.Models.CertificationExpirationDate
#   CertificationName: OrangeButton.Models.CertificationName
#   CertificationStandard: OrangeButton.Models.CertificationStandard
#   Checksum: OrangeButton.Models.Checksum
#   ChecksumDetail: OrangeButton.Models.ChecksumDetail
#   ChecksumKey: OrangeButton.Models.ChecksumKey
#   ChecksumType: OrangeButton.Models.ChecksumType
#   City: OrangeButton.Models.City
#   Comment: OrangeButton.Models.Comment
#   CommentDate: OrangeButton.Models.CommentDate
#   CommentID: OrangeButton.Models.CommentID
#   CommentText: OrangeButton.Models.CommentText
#   Component: OrangeButton.Models.Component
#   ComponentName: OrangeButton.Models.ComponentName
#   ComponentType: OrangeButton.Models.ComponentType
#   ComponentUUID: OrangeButton.Models.ComponentUUID
#   Connection: OrangeButton.Models.Connection
#   ConnectionId: OrangeButton.Models.ConnectionId
#   ConnectionType: OrangeButton.Models.ConnectionType
#   Contact: OrangeButton.Models.Contact
#   ContactID: OrangeButton.Models.ContactID
#   ContactTimezone: OrangeButton.Models.ContactTimezone
#   ContactType: OrangeButton.Models.ContactType
#   Country: OrangeButton.Models.Country
#   County: OrangeButton.Models.County
#   CreditRating: OrangeButton.Models.CreditRating
#   CreditScore: OrangeButton.Models.CreditScore
#   CreditScoreSource: OrangeButton.Models.CreditScoreSource
#   CryptographicKeyID: OrangeButton.Models.CryptographicKeyID
#   Description: OrangeButton.Models.Description
#   Device1: OrangeButton.Models.Device1
#   DeviceName: OrangeButton.Models.DeviceName
#   DeviceType: OrangeButton.Models.DeviceType
#   DeviceUUID: OrangeButton.Models.DeviceUUID
#   Dimension: OrangeButton.Models.Dimension
#   Document: OrangeButton.Models.Document
#   DocumentDate: OrangeButton.Models.DocumentDate
#   DocumentId: OrangeButton.Models.DocumentId
#   DocumentName: OrangeButton.Models.DocumentName
#   DocumentType: OrangeButton.Models.DocumentType
#   DocumentUrl: OrangeButton.Models.DocumentUrl
#   Elevation: OrangeButton.Models.Elevation
#   Email: OrangeButton.Models.Email
#   Entity: OrangeButton.Models.Entity
#   EntityRole: OrangeButton.Models.EntityRole
#   FileFolderURL: OrangeButton.Models.FileFolderURL
#   Firmware: OrangeButton.Models.Firmware
#   FirmwareVersion: OrangeButton.Models.FirmwareVersion
#   FirstName: OrangeButton.Models.FirstName
#   FromDeviceId: OrangeButton.Models.FromDeviceId
#   GatewayHook: OrangeButton.Models.GatewayHook
#   GatewayHookExecution: OrangeButton.Models.GatewayHookExecution
#   GatewayHookResult: OrangeButton.Models.GatewayHookResult
#   Height: OrangeButton.Models.Height
#   HomePhone: OrangeButton.Models.HomePhone
#   HookStatus: OrangeButton.Models.HookStatus
#   Identifier: OrangeButton.Models.Identifier
#   IdentifierType: OrangeButton.Models.IdentifierType
#   Info: OrangeButton.Models.Info
#   InServiceDate: OrangeButton.Models.InServiceDate
#   IsMaintainable: OrangeButton.Models.IsMaintainable
#   LastName: OrangeButton.Models.LastName
#   Latitude: OrangeButton.Models.Latitude
#   LegalEntityIdentifier: OrangeButton.Models.LegalEntityIdentifier
#   Length: OrangeButton.Models.Length
#   Location: OrangeButton.Models.Location
#   LocationDeterminationMethod: OrangeButton.Models.LocationDeterminationMethod
#   LocationID: OrangeButton.Models.LocationID
#   LocationType: OrangeButton.Models.LocationType
#   Longitude: OrangeButton.Models.Longitude
#   MaintDateLast: OrangeButton.Models.MaintDateLast
#   ManufacturerUPC: OrangeButton.Models.ManufacturerUPC
#   Mass: OrangeButton.Models.Mass
#   MiddleName: OrangeButton.Models.MiddleName
#   MobilePhone: OrangeButton.Models.MobilePhone
#   ModuleOrientation: OrangeButton.Models.ModuleOrientation
#   Node: OrangeButton.Models.Node
#   NodeUUID: OrangeButton.Models.NodeUUID
#   Orientation: OrangeButton.Models.Orientation
#   Package: OrangeButton.Models.Package
#   PaymentMethod: OrangeButton.Models.PaymentMethod
#   PaymentMethodName: OrangeButton.Models.PaymentMethodName
#   PaymentToken: OrangeButton.Models.PaymentToken
#   PlatformIdentifier: OrangeButton.Models.PlatformIdentifier
#   PreferredContactMethod: OrangeButton.Models.PreferredContactMethod
#   ProdCertification: OrangeButton.Models.ProdCertification
#   ProdCode: OrangeButton.Models.ProdCode
#   ProdDatasheet: OrangeButton.Models.ProdDatasheet
#   ProdID: OrangeButton.Models.ProdID
#   ProdInstruction: OrangeButton.Models.ProdInstruction
#   ProdMfr: OrangeButton.Models.ProdMfr
#   ProdName: OrangeButton.Models.ProdName
#   ProdSpecification: OrangeButton.Models.ProdSpecification
#   ProdType: OrangeButton.Models.ProdType
#   Product: OrangeButton.Models.Product
#   ProductLineItem: OrangeButton.Models.ProductLineItem
#   PVArray1: OrangeButton.Models.PVArray1
#   PVArrayID: OrangeButton.Models.PVArrayID
#   PVColladaFileID: OrangeButton.Models.PVColladaFileID
#   PVColladaID: OrangeButton.Models.PVColladaID
#   PVString1: OrangeButton.Models.PVString1
#   PVStringID: OrangeButton.Models.PVStringID
#   PVSystem: OrangeButton.Models.PVSystem
#   Quantity: OrangeButton.Models.Quantity
#   Roll: OrangeButton.Models.Roll
#   RoofPlaneID: OrangeButton.Models.RoofPlaneID
#   Scope: OrangeButton.Models.Scope
#   ScopeID: OrangeButton.Models.ScopeID
#   ScopeType: OrangeButton.Models.ScopeType
#   SerialNum: OrangeButton.Models.SerialNum
#   SourceName: OrangeButton.Models.SourceName
#   SpecificationName: OrangeButton.Models.SpecificationName
#   SpecificationType: OrangeButton.Models.SpecificationType
#   SpecificationUnit: OrangeButton.Models.SpecificationUnit
#   SpecificationValue: OrangeButton.Models.SpecificationValue
#   StateProvince: OrangeButton.Models.StateProvince
#   SubstituteProduct: OrangeButton.Models.SubstituteProduct
#   SupportedDocument: OrangeButton.Models.SupportedDocument
#   Tag: OrangeButton.Models.Tag
#   TaxID: OrangeButton.Models.TaxID
#   TaxonomyElementBoolean: OrangeButton.Models.TaxonomyElementBoolean
#   TaxonomyElementInteger: OrangeButton.Models.TaxonomyElementInteger
#   TaxonomyElementNumber: OrangeButton.Models.TaxonomyElementNumber
#   TaxonomyElementString: OrangeButton.Models.TaxonomyElementString
#   TestLab: OrangeButton.Models.TestLab
#   TestLabName: OrangeButton.Models.TestLabName
#   Tilt: OrangeButton.Models.Tilt
#   Title: OrangeButton.Models.Title
#   ToDeviceId: OrangeButton.Models.ToDeviceId
#   URL: OrangeButton.Models.URL
#   Warranty: OrangeButton.Models.Warranty
#   WarrantyDuration: OrangeButton.Models.WarrantyDuration
#   WarrantyEffectiveDate: OrangeButton.Models.WarrantyEffectiveDate
#   WarrantyExpirationDate: OrangeButton.Models.WarrantyExpirationDate
#   WarrantyID: OrangeButton.Models.WarrantyID
#   WarrantyName: OrangeButton.Models.WarrantyName
#   WarrantyType: OrangeButton.Models.WarrantyType
#   Weight: OrangeButton.Models.Weight
#   Width: OrangeButton.Models.Width
#   WorkPhone: OrangeButton.Models.WorkPhone
#   ZipPostalCode: OrangeButton.Models.ZipPostalCode
# typeMapping:
#   Address: OB_Address